nyc311_dbt:
  outputs:
    dev:
      account: EWFENRD-SL16915
      database: nyc311
      password: Mamaliza2001!!
      role: ACCOUNTADMIN
      schema: silver
      threads: 6
      type: snowflake
      user: tihim
      warehouse: nyc311_wh
  target: dev